// This file is intentionally left minimal since the localized layout lives in /app/[locale]/layout.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // The actual HTML structure is defined in /app/[locale]/layout.tsx via next-intl
  return <>{children}</>;
}
